name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      matrix:
        experimental: [false]

        os:
          - ubuntu

        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - 3.3

        include:
          - os: macos
            ruby: 3.3
          - experimental: true
            os: ubuntu
            ruby: head
          - experimental: true
            os: ubuntu
            ruby: 2.7
            env: BUNDLE_GEMFILE=gems/rack-v1.rb
          - experimental: true
            os: ubuntu
            ruby: 3.2
            env: BUNDLE_GEMFILE=gems/rack-v2.rb
          # enable when rack v3 is supported
          # - experimental: true
          #  os: ubuntu
          #  ruby: 3.2
          #  env: BUNDLE_GEMFILE=gems/rack-head.rb

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}

    - name: Install dependencies
      run: ${{matrix.env}} bundle install

    - name: Run tests
      run: ${{matrix.env}} bundle exec rake
